package main

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/enr/paq/internal/config"
	"github.com/enr/paq/internal/ui"
	"github.com/spf13/cobra"
)

var (
	flagImportAs      string
	flagImportDest    string
	flagImportVersion string
	flagImportWrite   bool
	flagImportForce   bool
)

var importCmd = &cobra.Command{
	Use:   "import <spec>",
	Short: "Generate a default manifest entry for a registry tool",
	Long: "Generate a default [apps.<name>] manifest entry for a tool defined in the registry.\n" +
		"By default the entry is printed to stdout; pass --write to add it to your manifest.",
	Example: `  paq import ripgrep                                  # print the generated entry
  paq import ripgrep --write                          # add it to your manifest
  paq import ripgrep --as rg --dest ~/bin/rg --write   # customize name/dest, then:
  paq install rg`,
	Args: cobra.ExactArgs(1),
	RunE: runImport,
}

func init() {
	importCmd.Flags().StringVarP(&flagImportAs, "as", "a", "", "Name for the manifest entry (default: spec name)")
	importCmd.Flags().StringVar(&flagImportDest, "dest", "", "Install destination (default: derived from the spec)")
	importCmd.Flags().StringVar(&flagImportVersion, "version", "", `Version to pin (default: "latest")`)
	importCmd.Flags().BoolVarP(&flagImportWrite, "write", "w", false, "Add the entry to the manifest instead of printing it")
	importCmd.Flags().BoolVarP(&flagImportForce, "force", "f", false, "Overwrite an existing entry (requires --write)")
	rootCmd.AddCommand(importCmd)
}

func runImport(cmd *cobra.Command, args []string) error {
	cfg, err := loadConfig()
	if err != nil {
		return err
	}

	defName := args[0]
	spec, ok := cfg.Specs[defName]
	if !ok {
		hint := "list available definitions with `paq registry`"
		if s := similarSpecs(cfg.Specs, defName); len(s) > 0 {
			hint = fmt.Sprintf("did you mean: %s?", strings.Join(s, ", "))
		}
		return hintError{msg: fmt.Sprintf("spec %q not found in registry", defName), hint: hint}
	}

	key := defName
	if flagImportAs != "" {
		key = flagImportAs
	}
	if !validAppKey(key) {
		return fmt.Errorf("invalid app name %q: use only letters, digits, '-' or '_'", key)
	}

	// Default version for the generated manifest entry:
	//   explicit --version > the spec's default_version > "latest".
	// Writing the concrete default_version makes the manifest self-documenting;
	// the user explicitly opts into "latest" for live resolution.
	ver := defaultImportVersion(spec)
	if flagImportVersion != "" {
		ver = flagImportVersion
	}

	dest := flagImportDest
	if dest == "" {
		dest = config.DefaultDest(spec, key, cfg.Defaults)
	}

	entry := config.AppEntry{Use: defName, Version: ver, Dest: dest}

	// If the entry stays on "latest" but the spec cannot resolve it, warn
	// (without blocking) that an explicit version needs to be pinned.
	if strings.EqualFold(ver, "latest") {
		req := latestRequestFor(spec)
		if !req.Resolvable() {
			ui.Warn("%q cannot resolve \"latest\"", defName)
			ui.Hint("set an explicit version, e.g. `paq import %s --version <v>`", defName)
		}
	}

	block := renderAppEntryTOML(key, entry)

	if !flagImportWrite {
		if ui.Global.JSON {
			data, _ := json.MarshalIndent(map[string]any{"app": key, "entry": entry}, "", "  ")
			fmt.Println(string(data))
		} else {
			fmt.Print(block)
		}
		if path, err := config.UserManifestPath(); err == nil {
			ui.Hint("re-run with --write to add it to %s", path)
		}
		return nil
	}

	if _, exists := cfg.Apps[key]; exists && !flagImportForce {
		return hintError{
			msg:  fmt.Sprintf("app %q already exists in the manifest", key),
			hint: "use --force to overwrite, or choose another name with --as",
		}
	}

	path, err := config.WriteManifestEntry(key, block, flagImportForce)
	if err != nil {
		return fmt.Errorf("write manifest entry: %w", err)
	}
	ui.OK("imported %s → %s", key, path)
	ui.Hint("install it with `paq install %s`", key)
	return nil
}

// defaultImportVersion picks the default version for a generated entry:
// the spec's concrete default_version if present, otherwise "latest".
func defaultImportVersion(spec config.Spec) string {
	if spec.DefaultVersion != "" {
		return spec.DefaultVersion
	}
	return "latest"
}

// renderAppEntryTOML produces the "[apps.<key>]" block with only the set fields.
func renderAppEntryTOML(key string, e config.AppEntry) string {
	var b strings.Builder
	b.WriteString("# generated by 'paq import'\n")
	fmt.Fprintf(&b, "[apps.%s]\n", key)
	if e.Use != "" {
		fmt.Fprintf(&b, "use = %q\n", e.Use)
	}
	if e.Version != "" {
		fmt.Fprintf(&b, "version = %q\n", e.Version)
	}
	if e.Dest != "" {
		fmt.Fprintf(&b, "dest = %q\n", e.Dest)
	}
	return b.String()
}

// validAppKey verifies that the app key is a simple identifier, so that
// valid TOML can be generated without needing to quote the key.
func validAppKey(key string) bool {
	if key == "" {
		return false
	}
	for _, r := range key {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_':
		default:
			return false
		}
	}
	return true
}
