[zipp]
backend = "github"
repo = "enr/zipp"
asset = "zipp-{{version}}_{{os}}_{{arch}}.zip"
archive = "zip"
chmod = "0755"
# The archive contains a top-level dir (zipp-<ver>_<os>_<arch>/) with the
# three binaries: installed as standalone executables in the bin dir (dest).
strip_components = 1
binaries = [
  { from = "zipts{{ext}}" },
  { from = "zipls{{ext}}" },
  { from = "zipw{{ext}}" },
]
