package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pelletier/go-toml/v2"
)

// LockEntry is one app's pinned resolution in the lockfile: the version paq
// resolved (and the sha256 it installed) the last time it ran a live
// "latest" resolution for that app.
type LockEntry struct {
	Version string `toml:"version"`
	SHA256  string `toml:"sha256,omitempty"`
}

// Lock is the parsed content of paq.lock.toml: one LockEntry per app name.
type Lock struct {
	Apps map[string]LockEntry `toml:"apps"`
}

// LockPath returns the path of the lockfile: it always lives next to the
// user manifest (so --config/PAQ_CONFIG relocate both together).
func LockPath() (string, error) {
	cfgPath, err := userConfigPath()
	if err != nil {
		return "", err
	}
	return filepath.Join(filepath.Dir(cfgPath), "paq.lock.toml"), nil
}

// LoadLock loads the lockfile. A missing file is not an error: it returns an
// empty Lock, exactly like LoadUserConfig treats a missing manifest — most
// manifests have no lockfile yet, and that's normal, not broken.
func LoadLock() (*Lock, error) {
	path, err := LockPath()
	if err != nil {
		return &Lock{Apps: map[string]LockEntry{}}, nil
	}

	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return &Lock{Apps: map[string]LockEntry{}}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read lockfile %s: %w", path, err)
	}

	var lock Lock
	if err := toml.Unmarshal(data, &lock); err != nil {
		return nil, fmt.Errorf("parse lockfile %s: %w", path, err)
	}
	if lock.Apps == nil {
		lock.Apps = map[string]LockEntry{}
	}
	return &lock, nil
}

// WriteLockEntry sets (or overwrites) appName's lock entry and rewrites the
// lockfile. Used after a live "latest" resolution, so a later `paq install`
// (on this machine or another sharing the manifest+lockfile) reproduces the
// same version instead of resolving "latest" again and possibly landing on a
// newer release.
func WriteLockEntry(appName string, entry LockEntry) error {
	lock, err := LoadLock()
	if err != nil {
		return err
	}
	lock.Apps[appName] = entry
	return saveLock(lock)
}

// DeleteLockEntry removes appName's lock entry, if any. A no-op (no error)
// when the lockfile doesn't exist or has no entry for it.
func DeleteLockEntry(appName string) error {
	lock, err := LoadLock()
	if err != nil {
		return err
	}
	if _, ok := lock.Apps[appName]; !ok {
		return nil
	}
	delete(lock.Apps, appName)
	return saveLock(lock)
}

// saveLock writes the lockfile atomically (temp file + rename), with entries
// sorted by app name: the file is meant to be committed to version control,
// and go-toml's map encoding order is not stable, which would otherwise
// produce a spurious diff on every write.
func saveLock(lock *Lock) error {
	path, err := LockPath()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}

	names := make([]string, 0, len(lock.Apps))
	for name := range lock.Apps {
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("# generated by paq — do not edit by hand; refreshed by `paq upgrade`\n")
	for _, name := range names {
		e := lock.Apps[name]
		fmt.Fprintf(&b, "\n[apps.%s]\n", name)
		fmt.Fprintf(&b, "version = %q\n", e.Version)
		if e.SHA256 != "" {
			fmt.Fprintf(&b, "sha256 = %q\n", e.SHA256)
		}
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("write lockfile: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return fmt.Errorf("replace lockfile: %w", err)
	}
	return nil
}
