package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const rgBlock = "# generated by 'paq import'\n[apps.rg]\nuse = \"ripgrep\"\nversion = \"latest\"\ndest = \"~/.local/bin/rg{{ext}}\"\n"

func TestWriteManifestEntryCreatesFile(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)

	path, err := WriteManifestEntry("rg", rgBlock, false)
	if err != nil {
		t.Fatalf("write: %v", err)
	}
	if path != filepath.Join(dir, "paq", "config.toml") {
		t.Errorf("unexpected path: %s", path)
	}

	cfg, err := LoadUserConfig()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	app, ok := cfg.Apps["rg"]
	if !ok {
		t.Fatal("rg not found after write")
	}
	if app.Use != "ripgrep" || app.Version != "latest" {
		t.Errorf("entry = %+v", app)
	}
}

func TestWriteManifestEntryPreservesExisting(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)

	manifest := filepath.Join(dir, "paq", "config.toml")
	os.MkdirAll(filepath.Dir(manifest), 0755)
	original := "# my hand-written manifest\n[apps.bat]\nuse = \"bat\"\nversion = \"latest\"\ndest = \"~/.local/bin/bat\"\n"
	os.WriteFile(manifest, []byte(original), 0644)

	if _, err := WriteManifestEntry("rg", rgBlock, false); err != nil {
		t.Fatalf("write: %v", err)
	}

	data, _ := os.ReadFile(manifest)
	got := string(data)
	if !strings.Contains(got, "# my hand-written manifest") {
		t.Error("existing comment was not preserved")
	}
	if !strings.Contains(got, "[apps.bat]") || !strings.Contains(got, "[apps.rg]") {
		t.Errorf("both entries should be present; got:\n%s", got)
	}
}

func TestWriteManifestEntryRejectsDuplicate(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)

	if _, err := WriteManifestEntry("rg", rgBlock, false); err != nil {
		t.Fatalf("first write: %v", err)
	}
	// Senza overwrite, riscrivere la stessa chiave deve fallire (TOML duplicato).
	if _, err := WriteManifestEntry("rg", rgBlock, false); err == nil {
		t.Error("expected error writing duplicate entry without overwrite")
	}
}

func TestWriteManifestEntryOverwrite(t *testing.T) {
	dir := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", dir)

	if _, err := WriteManifestEntry("rg", rgBlock, false); err != nil {
		t.Fatalf("first write: %v", err)
	}
	newBlock := "[apps.rg]\nuse = \"ripgrep\"\nversion = \"14.1.0\"\ndest = \"~/bin/rg\"\n"
	if _, err := WriteManifestEntry("rg", newBlock, true); err != nil {
		t.Fatalf("overwrite: %v", err)
	}

	cfg, err := LoadUserConfig()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	if got := cfg.Apps["rg"]; got.Version != "14.1.0" || got.Dest != "~/bin/rg" {
		t.Errorf("entry not overwritten: %+v", got)
	}
	// Non devono restare due tabelle [apps.rg].
	data, _ := os.ReadFile(filepath.Join(dir, "paq", "config.toml"))
	if n := strings.Count(string(data), "[apps.rg]"); n != 1 {
		t.Errorf("expected exactly one [apps.rg], got %d:\n%s", n, data)
	}
}

func TestRemoveAppTable(t *testing.T) {
	content := "[apps.bat]\nuse = \"bat\"\n\n[apps.rg]\nuse = \"ripgrep\"\n\n[apps.hugo]\nuse = \"hugo\"\n"
	got := removeAppTable(content, "rg")
	if strings.Contains(got, "[apps.rg]") || strings.Contains(got, "ripgrep") {
		t.Errorf("rg table not removed:\n%s", got)
	}
	if !strings.Contains(got, "[apps.bat]") || !strings.Contains(got, "[apps.hugo]") {
		t.Errorf("other tables should remain:\n%s", got)
	}
}
