package config

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

const rgBlock = "# generated by 'paq import'\n[apps.rg]\nuse = \"ripgrep\"\nversion = \"latest\"\ndest = \"~/.local/bin/rg{{ext}}\"\n"

// withConfigHome points userConfigPath at dir, on Linux/macOS (XDG_CONFIG_HOME)
// and Windows (APPDATA) alike.
func withConfigHome(t *testing.T, dir string) {
	t.Helper()
	t.Setenv("XDG_CONFIG_HOME", dir)
	if runtime.GOOS == "windows" {
		t.Setenv("APPDATA", dir)
	}
}

func TestWriteManifestEntryCreatesFile(t *testing.T) {
	dir := t.TempDir()
	withConfigHome(t, dir)

	path, err := WriteManifestEntry("rg", rgBlock, false)
	if err != nil {
		t.Fatalf("write: %v", err)
	}
	if path != filepath.Join(dir, "paq", "config.toml") {
		t.Errorf("unexpected path: %s", path)
	}

	cfg, err := LoadUserConfig()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	app, ok := cfg.Apps["rg"]
	if !ok {
		t.Fatal("rg not found after write")
	}
	if app.Use != "ripgrep" || app.Version != "latest" {
		t.Errorf("entry = %+v", app)
	}
}

func TestWriteManifestEntryPreservesExisting(t *testing.T) {
	dir := t.TempDir()
	withConfigHome(t, dir)

	manifest := filepath.Join(dir, "paq", "config.toml")
	os.MkdirAll(filepath.Dir(manifest), 0755)
	original := "# my hand-written manifest\n[apps.bat]\nuse = \"bat\"\nversion = \"latest\"\ndest = \"~/.local/bin/bat\"\n"
	os.WriteFile(manifest, []byte(original), 0644)

	if _, err := WriteManifestEntry("rg", rgBlock, false); err != nil {
		t.Fatalf("write: %v", err)
	}

	data, _ := os.ReadFile(manifest)
	got := string(data)
	if !strings.Contains(got, "# my hand-written manifest") {
		t.Error("existing comment was not preserved")
	}
	if !strings.Contains(got, "[apps.bat]") || !strings.Contains(got, "[apps.rg]") {
		t.Errorf("both entries should be present; got:\n%s", got)
	}
}

func TestWriteManifestEntryRejectsDuplicate(t *testing.T) {
	dir := t.TempDir()
	withConfigHome(t, dir)

	if _, err := WriteManifestEntry("rg", rgBlock, false); err != nil {
		t.Fatalf("first write: %v", err)
	}
	// Without overwrite, rewriting the same key must fail (duplicate TOML key).
	if _, err := WriteManifestEntry("rg", rgBlock, false); err == nil {
		t.Error("expected error writing duplicate entry without overwrite")
	}
}

func TestWriteManifestEntryOverwrite(t *testing.T) {
	dir := t.TempDir()
	withConfigHome(t, dir)

	if _, err := WriteManifestEntry("rg", rgBlock, false); err != nil {
		t.Fatalf("first write: %v", err)
	}
	newBlock := "[apps.rg]\nuse = \"ripgrep\"\nversion = \"14.1.0\"\ndest = \"~/bin/rg\"\n"
	if _, err := WriteManifestEntry("rg", newBlock, true); err != nil {
		t.Fatalf("overwrite: %v", err)
	}

	cfg, err := LoadUserConfig()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	if got := cfg.Apps["rg"]; got.Version != "14.1.0" || got.Dest != "~/bin/rg" {
		t.Errorf("entry not overwritten: %+v", got)
	}
	// There must not be two [apps.rg] tables left.
	data, _ := os.ReadFile(filepath.Join(dir, "paq", "config.toml"))
	if n := strings.Count(string(data), "[apps.rg]"); n != 1 {
		t.Errorf("expected exactly one [apps.rg], got %d:\n%s", n, data)
	}
}

func TestRemoveAppTable(t *testing.T) {
	content := "[apps.bat]\nuse = \"bat\"\n\n[apps.rg]\nuse = \"ripgrep\"\n\n[apps.hugo]\nuse = \"hugo\"\n"
	got := removeAppTable(content, "rg")
	if strings.Contains(got, "[apps.rg]") || strings.Contains(got, "ripgrep") {
		t.Errorf("rg table not removed:\n%s", got)
	}
	if !strings.Contains(got, "[apps.bat]") || !strings.Contains(got, "[apps.hugo]") {
		t.Errorf("other tables should remain:\n%s", got)
	}
}

func TestSetManifestAppVersion(t *testing.T) {
	for _, tc := range []struct {
		name, orig, want string
	}{
		{
			name: "replaces the version line",
			orig: "[apps.rg]\nuse = \"ripgrep\"\nversion = \"latest\"\n\n[apps.bat]\nversion = \"0.24.0\"\n",
			want: "[apps.rg]\nuse = \"ripgrep\"\nversion = \"14.1.0\"\n\n[apps.bat]\nversion = \"0.24.0\"\n",
		},
		{
			name: "adds a missing version below the header",
			orig: "[apps.bat]\nversion = \"0.24.0\"\n\n[apps.rg]\nuse = \"ripgrep\"\n\n[apps.rg.os]\nversion = \"x\"\n",
			want: "[apps.bat]\nversion = \"0.24.0\"\n\n[apps.rg]\nversion = \"14.1.0\"\nuse = \"ripgrep\"\n\n[apps.rg.os]\nversion = \"x\"\n",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			withConfigHome(t, dir)
			path := filepath.Join(dir, "paq", "config.toml")
			os.MkdirAll(filepath.Dir(path), 0755)
			if err := os.WriteFile(path, []byte(tc.orig), 0644); err != nil {
				t.Fatal(err)
			}

			if _, err := SetManifestAppVersion("rg", "14.1.0"); err != nil {
				t.Fatalf("SetManifestAppVersion: %v", err)
			}
			data, _ := os.ReadFile(path)
			if string(data) != tc.want {
				t.Errorf("manifest =\n%s\nwant\n%s", data, tc.want)
			}
		})
	}
}

// An app declared without its own [apps.<key>] header cannot be edited line
// by line: the manifest must be left untouched.
func TestSetManifestAppVersionInlineTableFails(t *testing.T) {
	dir := t.TempDir()
	withConfigHome(t, dir)
	path := filepath.Join(dir, "paq", "config.toml")
	os.MkdirAll(filepath.Dir(path), 0755)
	orig := "[apps]\nrg = { use = \"ripgrep\", version = \"latest\" }\n"
	if err := os.WriteFile(path, []byte(orig), 0644); err != nil {
		t.Fatal(err)
	}

	if _, err := SetManifestAppVersion("rg", "14.1.0"); err == nil {
		t.Fatal("expected an error, got nil")
	}
	if data, _ := os.ReadFile(path); string(data) != orig {
		t.Errorf("manifest was modified:\n%s", data)
	}
}
