name: Cross-platform tests

on:
  push:
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test
        shell: bash
        run: ./.sdlc/test
      - name: Vet
        run: go vet ./...
